/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DiagGenPrueba.java
 *
 * Created on Aug 9, 2012, 9:31:10 PM
 */
package org.grupoia.main.tpdos.ptob.genprueba.gui;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import org.grupoia.main.tpdos.ptob.genprueba.Dado;
import org.grupoia.main.tpdos.ptob.genprueba.Dados;
import org.grupoia.main.tpdos.ptob.genprueba.MyColor;

/**
 *
 * @author fanky
 */
public class DiagGenPrueba extends javax.swing.JDialog {
    private static final String TITLE = "Generacion y Prueba";
    /** Creates new form DiagGenPrueba */
    public DiagGenPrueba(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
        setTitle(TITLE);
        setLocationRelativeTo(null);
    }
    private void init(){
        reiniciarColores();
    }
    private void initCombos() {

        cmbColor1.setModel(new DefaultComboBoxModel(Dado.COLORES_DISPONIBLES));
        cmbColor2.setModel(new DefaultComboBoxModel(Dado.COLORES_DISPONIBLES));
        cmbColor3.setModel(new DefaultComboBoxModel(Dado.COLORES_DISPONIBLES));
        cmbColor4.setModel(new DefaultComboBoxModel(Dado.COLORES_DISPONIBLES));
    }

    private void buscarCombinacion() {
        Dados dados = new Dados();
        dados.add(new Dado(lblColor1.getBackground()));
        dados.add(new Dado(lblColor2.getBackground()));
        dados.add(new Dado(lblColor3.getBackground()));
        dados.add(new Dado(lblColor4.getBackground()));
        
        boolean finalizo = false;
        //generar una posible solucion
        //configurar dados
        //verificar si el objetivo se cumplió
        //si no verifica, cambiar configuracion
        finalizo = dados.verificaConfig();
        if (!finalizo){
            dados.cambiaConfig();
            System.out.println("nueva config:"+dados);
            refreshLabels(dados);
        }else{
            btnBuscar.setEnabled(false);
        }
    }
    private void refreshLabels(Dados dados){
        lblColor1.setBackground(dados.get(0).getColor());
        lblColor2.setBackground(dados.get(1).getColor());
        lblColor3.setBackground(dados.get(2).getColor());
        lblColor4.setBackground(dados.get(3).getColor());
        
    }

    private void reiniciarColores() {
        Color defaultColor = Color.WHITE;
        lblColor1.setBackground(defaultColor);
        lblColor2.setBackground(defaultColor);
        lblColor3.setBackground(defaultColor);
        lblColor4.setBackground(defaultColor);
        initCombos();
        btnBuscar.setEnabled(true);
    }

    private void cerrar() {
        this.dispose();
    }

    private void cambiaColorLbl1() {
        MyColor myColor = (MyColor) cmbColor1.getSelectedItem();
        cambiaColor(myColor, lblColor1);
    }

    private void cambiaColorLbl2() {
        MyColor myColor = (MyColor) cmbColor2.getSelectedItem();
        cambiaColor(myColor, lblColor2);
    }

    private void cambiaColorLbl3() {
        MyColor myColor = (MyColor) cmbColor3.getSelectedItem();
        cambiaColor(myColor, lblColor3);
    }

    private void cambiaColorLbl4() {
        MyColor myColor = (MyColor) cmbColor4.getSelectedItem();
        cambiaColor(myColor, lblColor4);
    }
    private void cambiaColor(MyColor color, JLabel label){
        label.setBackground(color.getColor());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cmbColor1 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        cmbColor2 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        cmbColor3 = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        cmbColor4 = new javax.swing.JComboBox();
        lblColor1 = new javax.swing.JLabel();
        lblColor2 = new javax.swing.JLabel();
        lblColor3 = new javax.swing.JLabel();
        lblColor4 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar);

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnReiniciar);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridLayout(0, 4));

        cmbColor1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbColor1ActionPerformed(evt);
            }
        });
        jPanel3.add(cmbColor1);

        jPanel2.add(jPanel3);

        cmbColor2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbColor2ActionPerformed(evt);
            }
        });
        jPanel4.add(cmbColor2);

        jPanel2.add(jPanel4);

        cmbColor3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbColor3ActionPerformed(evt);
            }
        });
        jPanel5.add(cmbColor3);

        jPanel2.add(jPanel5);

        cmbColor4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbColor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbColor4ActionPerformed(evt);
            }
        });
        jPanel6.add(cmbColor4);

        jPanel2.add(jPanel6);

        lblColor1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblColor1.setOpaque(true);
        jPanel2.add(lblColor1);

        lblColor2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblColor2.setOpaque(true);
        jPanel2.add(lblColor2);

        lblColor3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblColor3.setOpaque(true);
        jPanel2.add(lblColor3);

        lblColor4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblColor4.setOpaque(true);
        jPanel2.add(lblColor4);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarCombinacion();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        reiniciarColores();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        cerrar();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void cmbColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbColor1ActionPerformed
        cambiaColorLbl1();
    }//GEN-LAST:event_cmbColor1ActionPerformed

    private void cmbColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbColor2ActionPerformed
        cambiaColorLbl2();
    }//GEN-LAST:event_cmbColor2ActionPerformed

    private void cmbColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbColor3ActionPerformed
        cambiaColorLbl3();
    }//GEN-LAST:event_cmbColor3ActionPerformed

    private void cmbColor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbColor4ActionPerformed
        cambiaColorLbl4();
    }//GEN-LAST:event_cmbColor4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagGenPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagGenPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagGenPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagGenPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DiagGenPrueba dialog = new DiagGenPrueba(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                dialog.dispose();
                System.exit(0);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JComboBox cmbColor1;
    private javax.swing.JComboBox cmbColor2;
    private javax.swing.JComboBox cmbColor3;
    private javax.swing.JComboBox cmbColor4;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblColor1;
    private javax.swing.JLabel lblColor2;
    private javax.swing.JLabel lblColor3;
    private javax.swing.JLabel lblColor4;
    // End of variables declaration//GEN-END:variables
}
